import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <ul className="flex gap-5 text-red-500 border border-zinc-900">
            <li>
              <Link href="/reviews">reviews</Link>
            </li>
            <li>
              <Link href="/about">about</Link>
            </li>
          </ul>
        </header>
        <main>{children}</main>
        <footer>
          Game data and images courtesy of{' '}
          <a href="https://rawg.io/" target="_blank">
            RAWG
          </a>
        </footer>
      </body>
    </html>
  );
}
